domain: transit.lan

frontend:
  image:
    repository: ghcr.io/nanolookc/transport-map-frontend
    tag: "sha-DEV"
  replicas: 1
  port: 3000

backend:
  image:
    repository: ghcr.io/nanolookc/transport-map-backend
    tag: "sha-DEV"
  replicas: 2
  workerReplicas: 1
  port: 3000
  envFromConfigMap: transit-backend-config
  envFromSecret: transit-backend-secrets
